
#name: default using project name

services:
  container1:
    image: mysql
    container_name: mysql_project_container
    environment:
      - MYSQL_ROOT_PASSWORD = mysql
      - MYSQL_TCP_PORT = 15000
#    ports:
#      - 16000:3306
    network_mode: host
    volumes:
      - ~/project:/var/lib/mysql